### ISSUE TITLE
该connect是否需要Confluent平台的Schema Registry？

### ISSUE THREAD

**Issue by znoodl** [teambition/kafka-connect-mongo#1]
请问这个和https://github.com/DataReply/kafka-connect-mongodb
的区别除了读取mongodb全部数据而不是读取oplog外，是否和DataReply的一样需要Confluent平台的Schema Registry？
谢谢！

**Comment by sailxjx** [comment]
需要的

**Comment by znoodl** [comment]
谢谢，能否出一个不需要Schema Registry的版本？DataReply作者有打算不过好像一直没时间更新。

**Comment by sailxjx** [comment]
没有这个计划，产生这个需求的原因是什么？

**Comment by znoodl** [comment]
目前的设计只使用了原生的kafka，没有Confluent平台依赖

**Comment by sailxjx** [comment]
如果不用 confluent 的话，用 connector 就没有意义了。
写个脚本，或者用其他的框架好了，譬如 samza。
