### ISSUE TITLE
Using org.apache.kafka.connect as your package namespace raises problem when using the connector with Landoop's Lenses.

### ISSUE THREAD

**Issue by indaco789** [teambition/kafka-connect-mongo#12]
When trying to use the connector with Landoop's lenses (Kafka@0.11.0) the connector is blacklisted by Kafka's package name-check that is run @ https://github.com/apache/kafka/blob/0.11.0/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/isolation/PluginUtils.java 

If the package name is `org.apache.kafka` when trying to create a new connector Kafka connect will fail and exit execution @ https://github.com/apache/kafka/blob/0.11.0/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/isolation/Plugins.java#L161

After renaming the package to a different name and compiling the project, everything worked as expected.

**Comment by sailxjx** [comment]
@indaco789 You are right. I changed the package name in version 1.6.0, you may find the migration tips in the readme file https://github.com/teambition/kafka-connect-mongo#warning-when-upgrade-from-15x-to-160-please-read-the-messages-below
