### ISSUE TITLE
how to config

### ISSUE THREAD

**Issue by qinxiaohua** [teambition/kafka-connect-mongo#13]
log4j:WARN No appenders could be found for logger (org.apache.kafka.connect.mongo.tools.ImportJob).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

i'm .net progmer,new to java
thank you

**Comment by sailxjx** [comment]
@qinxiaohua just ignore the warnings :)

Or you can add these options in your `JAVA_OPTS` environment variable: `-Dlog4j.configuration=file:/path/to/your/log4j.properties`
