### ISSUE TITLE
record loss because of maxMessageSize?

### ISSUE THREAD

**Issue by sabinthomas** [teambition/kafka-connect-mongo#4]
EDIT: Editing my earlier question, after I reviewed the code some more, and understood the purpose of the TailableAwait cursor

Hi,
I believe I am losing records when using Mongo as a source. 

I reviewed the code in [DatabaseReader.kt](https://github.com/teambition/kafka-connect-mongo/blob/17abbcae41f4386897e2618b65990e30b907c1af/src/main/kotlin/org/apache/kafka/connect/mongo/DatabaseReader.kt#L61)

```kotlin
                // Stop pulling data when length of message is too large!
                while (messages.size > maxMessageSize) {
                    log.warn("Message overwhelm! database {}, docs {}, messages {}",
                            db,
                            count,
                            messages.size)
                    Thread.sleep(500)
                }
```
I believe the section of code where the Thread is put to sleep if it exceeds the maxMessageSize that is currently set to `2000` causes loss of record insertion into Mongo. Is there any alternative besides Thread.sleep()?

**Comment by sailxjx** [comment]
@sabinthomas Why would this causes loss of record? It just sleeps and handles the next record from the iterable cursor.

**Comment by sabinthomas** [comment]
@sailxjx you are right, although I can't seem to find a lot of good documentation on CursorType.TailableAwait.

Let me debug this some more. For some reason, I'm consistently not getting messages beyond maxMessageSize being inserted into my Mongo database. I'm using Mongo both as a source and a sink, and wonder if this may be causing some issues.

**Comment by sailxjx** [comment]
@sabinthomas When the message queue reach the max size and do not consume for a long time, you should check your kafka consumers.
You can start a new kafka-console-consumer in your terminal and check if these is some new coming messages

**Comment by sabinthomas** [comment]
Hi @sailxjx ,
I'm still debugging this, but haven't figured it out. I'm hoping you can help. 

Here's my configuration
`MongoDB (collectionA) --> source --> Kafka --> sink --> MongoDB (collectionB)`

When I insert 1039 records into collectionA, I don't see 1039 records being received by the sink. Here are my logs on the Source
```
connect-standalone[7584]: [2017-11-08 15:25:07,707] TRACE Polling records (org.apache.kafka.connect.mongo.MongoSourceTask:70)
connect-standalone[7584]: [2017-11-08 15:25:14,885] TRACE Document Document{{ts=Timestamp{seconds=1510172714, inc=715}, t=11, h=3199962434014278430, v=2, op=i, ns=collectionA, o=Document{{_id=5a03682a48c6fa7f5955fa2c, blah blah....}} (org.apache.kafka.connect.mongo.DatabaseReader:76)
... (~1000 records)
connect-standalone[7584]: [2017-11-08 15:25:40,879] INFO Finished WorkerSourceTask{id=mongo-source-connector-0} commitOffsets successfully in 1 ms (org.apache.kafka.connect.runtime.WorkerSourceTask:371)
```

But when I trace the Sink, I see the following
```
connect-standalone[7587]: [2017-11-08 15:24:40,538] DEBUG Receive records 0 (org.apache.kafka.connect.mongo.MongoSinkTask:43)
connect-standalone[7587]: [2017-11-08 15:24:40,539] INFO WorkerSinkTask{id=mongo-sink-connector-0} Committing offsets (org.apache.kafka.connect.runtime.WorkerSinkTask:272)
connect-standalone[7587]: [2017-11-08 15:24:40,542] WARN Commit of WorkerSinkTask{id=mongo-sink-connector-0} offsets timed out (org.apache.kafka.connect.runtime.WorkerSinkTask:172)
connect-standalone[7587]: [2017-11-08 15:25:17,761] DEBUG Receive records 4 (org.apache.kafka.connect.mongo.MongoSinkTask:43)
connect-standalone[7587]: [2017-11-08 15:25:17,761] TRACE Put record: SinkRecord{kafkaOffset=278321, timestampType=CreateTime} ConnectRecord{topic='in_collectionA', kafkaPartition=0, key=5a03682548c6fa7f5955f678, value=Struct{ts=1510172709,inc=1,id=5a03682548c6fa7f5955f678,database=collectionA,op=i,object={ "_id" : { "$oid" : "5a03682548c6fa7f5955f678" }, "ip" : "127.0.0.1", timestamp=1510172717758} (org.apache.kafka.connect.mongo.MongoSinkTask:46)
connect-standalone[7587]: [2017-11-08 15:25:17,823] DEBUG Receive records 16 (org.apache.kafka.connect.mongo.MongoSinkTask:43)
TRACE Put record: blah blah ...
connect-standalone[7587]: [2017-11-08 15:25:17,871] DEBUG Receive records 80 (org.apache.kafka.connect.mongo.MongoSinkTask:43)
TRACE Put record: blah blah ...
connect-standalone[7587]: [2017-11-08 15:25:18,194] DEBUG Receive records 3 (org.apache.kafka.connect.mongo.MongoSinkTask:43)
TRACE Put record: blah blah ...
connect-standalone[7587]: [2017-11-08 15:25:18,210] DEBUG Receive records 211 (org.apache.kafka.connect.mongo.MongoSinkTask:43)
TRACE Put record: blah blah ...
dev3 connect-standalone[7587]: [2017-11-08 15:26:40,539] DEBUG Receive records 0 (org.apache.kafka.connect.mongo.MongoSinkTask:43)
```

As you can see from the above, the sink has only received about `4+16+80+3+211`=`314` records and inserted them into collectionB. Do you know why it hasn't read the full ~1000 records that were inserted by the source?

**Comment by sailxjx** [comment]
Could you show the topic information by this command `kafka-topics --describe --zookeeper localhost:2181 --topic {your topic name}`

**Comment by sabinthomas** [comment]
Hi, its
```
$ kafka-topics --describe --zookeeper localhost:2181 --topic in_mytopic
Topic:in_mytopic	PartitionCount:1	ReplicationFactor:1	Configs:
	Topic: in_mytopic	Partition: 0	Leader: 0	Replicas: 0	Isr: 0
```

**Comment by sailxjx** [comment]
However, why your topic in the log of sink is called 'in_collectionA'?

**Comment by sabinthomas** [comment]
ah sorry, I edited the topic before I posted it here, it should be 
```
$ kafka-topics --describe --zookeeper localhost:2181 --topic in_collectionA
Topic:in_collectionA	PartitionCount:1	ReplicationFactor:1	Configs:
	Topic: in_collectionA	Partition: 0	Leader: 0	Replicas: 0	Isr: 0
```

**Comment by sabinthomas** [comment]
Thanks for confirming. When you say "clean transportation", are you suggesting that I run the "gradle import" job using the connector, or just to do an export from collectionA to collectionB within mongo?

**Comment by sailxjx** [comment]
I mean create a new collection A (or use another name to avoid confusing, maybe `alpha`), and pipe the data from `alpha` to collection `beta` through `alpha -> source -> kafka -> sink -> beta`.
Finally just compare the counts of both collections, if they're equal, the sink works, or the sink is broken for some reason.

**Comment by sabinthomas** [comment]
ah, i see. Ok let me try doing this in a new mongodb instance, and new kafka instance as well to minimize any overlap. Will post the results here in a day or two. Thanks for the assistance.
